//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypeNSaveWebForm.Models.Safeway.Baby
{
    using System;
    using System.Collections.Generic;
    
    public partial class BabyBathsAndSkinCare
    {
        public Nullable<double> price { get; }
        public string unitOfMeasure { get;  }
        public string name { get; }
        public Nullable<double> pricePer { get; }
        public string shelfName { get; }
        public string productReview_avgRating { get;}
        public string productReview_reviewCount { get;}
        public string productReview_isReviewWriteEligible { get;}
        public string productReview_isReviewDisplayEligible { get;}
        public string productReview_isForOnetimeReview { get;}
        public string productReview_reviewTemplateType { get;}
        public string promoDescription { get;}
        public string promoType { get;}
        public int ID { get;}
    }
}
