//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BabyAccessory
    {
        public Nullable<double> price { get; set; }
        public string unitOfMeasure { get; set; }
        public string name { get; set; }
        public Nullable<double> pricePer { get; set; }
        public string shelfName { get; set; }
        public string promoDescription { get; set; }
        public string promoType { get; set; }
        public int ID { get; set; }
    }
}
